### Build configuration ###

[build]
    command = "yarn build"
    publish = "public/"

    # Shared, default environment for all contexts
    [build.environment]
        NODE_ENV = "development"

### Deploy context-specific configuration ###

[context.production.environment]
    NODE_ENV = "production"

# TODO(dabrady) Make a staging environment?

### Build Plugins ###

# For configuring contextual environment variables in the Netlify UI.
# I use this for contextual secrets.
[[plugins]]
    package = 'netlify-plugin-contextual-env'
    [plugins.inputs]
        mode = 'prefix'

# For inlining build-time environment variables within Netlify Functions.
# I use this in conjunction with `netlify-plugin-contextual-env`.
[[plugins]]
    package = "netlify-plugin-inline-functions-env"
    [plugins.inputs]
        # TODO(dabrady) Figure out how to get this to work pre-build, as the generated
        # functions are much larger than my actual source (because dependencies)
        buildEvent = "onPostBuild"
