### Build configuration ###

[build]
    command = "yarn build"
    publish = "public/"

    # Shared, default environment for all contexts
    [build.environment]
        NODE_ENV = "development"

### Deploy context-specific configuration ###

[context.production.environment]
    NODE_ENV = "production"

# TODO(dabrady) Make a staging environment?
